### ISSUE TITLE
Split PodTemplateSpec out from JobTaskSpec

### ISSUE THREAD

**Issue by irvinlim** [furiko-io/furiko#72]
This is to kick-start work for #63. We will begin by splitting out PodTemplateSpec from the TaskSpec as a sub-field:

```yaml
task:
  template:
    pod:
      spec:
        containers: [ ... ]
```
